---
name: 🚀 Deploy

on:
  push:
    branches:
      - main
    paths:
      - "apps/aws/**"
      - "apps/web/**"
      - "apps/backend/**"
  workflow_dispatch:

env:
  ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: cd apps/aws && npm install

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Web App
        run: cd apps/web && npm install && npm run build

      - name: Deploy CDK stack
        run: cd apps/aws && cdk deploy --require-approval never
